config/routes.rb
Rails.application.routes.draw do
  resources :events, except: [ :index ]
  resources :classrooms
  
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root 'classrooms#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/classroom.rb
class Classroom < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :events
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  belongs_to :classroom

  validates_presence_of :title
  
  validates :start_time, date: { 
    after_or_equal_to: Proc.new { |obj| [Time.now, Time.beginning_of_workday(obj.start_time)].max },
    before: Proc.new { |obj| Time.end_of_workday(obj.start_time) }
  }

  validates :end_time, date: {
    after: :start_time,
    before_or_equal_to: Proc.new { |obj| Time.end_of_workday(obj.start_time || obj.end_time) }
  }

  validate :classroom_availability, if: Proc.new { will_save_change_to_classroom_id? || will_save_change_to_start_time? || will_save_change_to_end_time? }

private

  def classroom_availability
    if Event.exists?(["id <> ? AND classroom_id = ? AND end_time >= ? AND start_time < ?", id.to_i, classroom_id, start_time, end_time])
      errors.add :base, "The classroom is not available at the chosen time."
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :validatable

  enum role: [:user, :moderator]

  has_many :events, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def moderator_only!
    if !current_user.moderator?
      flash[:alert] = "This is a moderator only feature"
      redirect_to authenticated_root_url
    end
  end
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  before_action :set_classroom, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :moderator_only!, except: %i[ index show ]

  # GET /classrooms or /classrooms.json
  def index
    @classrooms = Classroom.all
  end

  # GET /classrooms/1 or /classrooms/1.json
  def show
    @events = Event.where(classroom: @classroom)
  end

  # GET /classrooms/new
  def new
    @classroom = Classroom.new
  end

  # GET /classrooms/1/edit
  def edit
  end

  # POST /classrooms or /classrooms.json
  def create
    @classroom = Classroom.new(classroom_params)

    respond_to do |format|
      if @classroom.save
        format.html { redirect_to @classroom, notice: "Classroom was successfully created." }
        format.json { render :show, status: :created, location: @classroom }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @classroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /classrooms/1 or /classrooms/1.json
  def update
    respond_to do |format|
      if @classroom.update(classroom_params)
        format.html { redirect_to @classroom, notice: "Classroom was successfully updated." }
        format.json { render :show, status: :ok, location: @classroom }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @classroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /classrooms/1 or /classrooms/1.json
  def destroy
    @classroom.destroy
    respond_to do |format|
      format.html { redirect_to classrooms_url, notice: "Classroom was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_classroom
      @classroom = Classroom.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def classroom_params
      params.require(:classroom).permit(:name)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :owner_only!, only: %i[ edit update destroy ]

  # GET /events or /events.json
  def index
    redirect_to classrooms_path
  end

  # GET /events/1 or /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new(start_time: params[:date],
                        end_time: params[:date],
                        user: current_user,
                        classroom_id: params[:classroom_id])
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    classroom = @event.classroom
    @event.destroy
    respond_to do |format|
      format.html { redirect_to classroom_path(classroom), notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:title, :start_time, :end_time, :user_id, :classroom_id)
    end

    def owner_only!
      unless @event.user == current_user
        flash[:alert] = "You have to own this event before taking this action."
        redirect_to classroom_path(@event.classroom)
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/classrooms/_form.html.erb
<%= form_with(model: classroom, local: true) do |form| %>
  <% if classroom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(classroom.errors.count, "error") %> prohibited this classroom from being saved:</h2>

      <ul>
        <% classroom.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/classrooms/edit.html.erb
<h1>Editing Classroom</h1>

<%= render 'form', classroom: @classroom %>

<%= link_to 'Show', @classroom %> |
<%= link_to 'Back', classrooms_path %>

app/views/classrooms/index.html.erb
<h1>Classrooms</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @classrooms.each do |classroom| %>
      <tr>
        <td><%= link_to classroom.name, classroom, class: "btn btn-primary" %></td>
        <% if current_user.moderator? %>
          <td><%= link_to 'Edit', edit_classroom_path(classroom) %></td>
          <td><%= link_to 'Destroy', classroom, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if current_user.moderator? %>
  <%= link_to 'New Classroom', new_classroom_path %>
<% end %>

app/views/classrooms/new.html.erb
<h1>New Classroom</h1>

<%= render 'form', classroom: @classroom %>

<%= link_to 'Back', classrooms_path %>

app/views/classrooms/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <p>
    <% if current_user.moderator? %>
      <%= link_to 'Edit', edit_classroom_path(@classroom) %> |
    <% end %>
    <%= link_to 'Back', classrooms_path %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= @classroom.name %>
  </p>

  <%= month_calendar(events: @events) do |date, events| %>
    <p class="text-right"><small><%= date.day %></small></p>

    <% events.each do |event| %>
      <p>
        <%= link_to "#{event.start_time.strftime("%I:%M%p")} #{event.title}", event_path(event), class: "badge badge-primary w-100" %>
      </p>
    <% end %>
    
    <%= link_to '+ New event', new_event_path(date: date, classroom_id: @classroom.id) %>
  <% end %>
</div>

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time %>
  </div>

  <div class="field">
    <%= form.label :end_time %>
    <%= form.datetime_select :end_time %>
  </div>

  <% if @event.classroom.blank? %>
    <div class="field">
      <%= form.label :classroom %>
      <%= form.collection_select :classroom_id, Classroom.order(:name), :id, :name %>
    </div>
  <% else %>
    <%= form.hidden_field :classroom_id %>
  <% end %>

  <%= form.hidden_field :user_id %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', event_path(@event) %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Start time</th>
      <th>End time</th>
      <th>User</th>
      <th>Classroom</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.start_time %></td>
        <td><%= event.end_time %></td>
        <td><%= event.user_id %></td>
        <td><%= event.classroom_id %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<% if @event.classroom.blank? %>
  <%= link_to 'Back', classrooms_path %>
<% else %>
  <%= link_to 'Back', classroom_path(@event.classroom) %>
<% end %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @event.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @event.end_time %>
</p>

<p>
  <strong>User:</strong>
  <%= @event.user.name %>
</p>

<p>
  <strong>Classroom:</strong>
  <%= @event.classroom.name %>
</p>

<% if @event.user == current_user %>
  <%= link_to 'Edit', edit_event_path(@event) %> |
  <%= link_to 'Destroy', @event, method: :delete, data: { confirm: 'Are you sure?' } %> |
<% end %>
<%= link_to 'Back', classroom_path(@event.classroom) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BloxChallenge</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= link_to "Sign out", destroy_user_session_path, :method => :delete if current_user %>

    <%= yield %>
  </body>
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>